dependencies:
  - conda-forge::feather-format
  - conda-forge::jupyter_contrib_nbextensions
  - conda-forge::jupyter_nbextensions_configurator
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - nodejs
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
